# Generated by Django 3.0.1 on 2020-03-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200301_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='regitration_date',
            new_name='registration_date',
        ),
    ]
